@startuml
'https://plantuml.com/sequence-diagram

!define ADD_CAR_COLOR #759bc7

hide footbox
skinparam sequenceMessageAlign center
skinparam sequence {
ParticipantBackgroundColor #1e4a7d
ParticipantFontColor white
}

box <font size=14>add-car\n ADD_CAR_COLOR
participant "CliRental" as CliRental
participant "<<class>>\nParser" as Parser
participant "<<class>>\nCarParser" as CarParser
participant "car :Car" as Car
participant "<<class>>\nCarList" as CarList
end box

CliRental -> Parser ++ : parse user input
Parser -> CarParser ++ : parse into Car object

create Car
CarParser -> Car ++
Car --> CarParser --
CarParser --> Parser --: car : Car

Parser -> CarList ++ : addCar(car)
CarList --> Parser --: car added to list
Parser --> CliRental --: exit status

@enduml