@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant ":FileHandler" as FileHandler
participant ":CarFile" as CarFile
participant ":Scanner" as scanner
participant "errorLines \n: ArrayList<Integer>" as ArrayList
participant ":Car" as Car
participant ":CarList" as CarList

 -> FileHandler: createAndLoadFiles()
activate FileHandler
    FileHandler -> CarFile : createCarFileIfNotExist()
    activate CarFile
        opt File does not exist
            CarFile -> FileHandler : createNewFile()
            FileHandler --> CarFile : return
        end opt
    CarFile --> FileHandler : return
    deactivate CarFile

FileHandler -> CarFile: loadCarDataIfExist()
activate CarFile
    opt File exists
        CarFile -> CarFile : loadCarData()
        activate CarFile


            create scanner
            CarFile -> scanner : new scanner()
            activate scanner
                scanner --> CarFile : return
            deactivate scanner

            create ArrayList
            CarFile -> ArrayList: new ArrayList<Integer>()
            activate ArrayList
                ArrayList --> CarFile : return
            deactivate ArrayList

            loop For each line in file
                CarFile -> scanner : hasNext()
                activate scanner
                    opt next line exists
                        CarFile -> CarFile: scanLineAndAddCar()
                        activate CarFile
                            CarFile -> scanner : nextLine()
                            activate scanner
                                alt parameters.length != Car.NUMBER_OF_PARAMETER
                                    CarFile -> ArrayList : add(line : int)
                                    activate ArrayList
                                    ArrayList --> CarFile : return
                                    deactivate ArrayList
                                else
                                    CarFile -> CarFile : addCarWithParameters(...)
                                    opt parameters are correctly formatted
                                    activate CarFile
                                        CarFile -> Car : new Car()
                                        activate Car
                                        Car --> CarFile : return
                                        deactivate Car
                                        CarFile -> CarList : addCarWithoutPrintingInfo(car : Car)
                                        activate CarList
                                            CarList -> CarList : add(car : Car)
                                            activate CarList
                                                CarList --> CarList : return
                                            deactivate CarList
                                        CarList --> CarFile : return
                                        deactivate CarList
                                    end opt
                                    CarFile --> CarFile : return
                                    deactivate CarFile
                                end alt
                            scanner --> CarFile : return
                            deactivate scanner
                        CarFile --> CarFile : return
                        deactivate CarFile
                    end opt
                scanner --> CarFile : return
                deactivate scanner
            end loop

        CarFile --> CarFile : return
        deactivate CarFile
    end opt
CarFile --> FileHandler : return
deactivate CarFile

<-- FileHandler : return
deactivate FileHandler
hide footbox
@enduml